const std = @import("std");

pub const max_nodes: usize = 256;
pub const max_edges: usize = 4096;
pub const max_route_nodes: usize = 256;

pub const widget_audio_output: u8 = 0x00;
pub const widget_audio_mixer: u8 = 0x02;
pub const widget_audio_selector: u8 = 0x03;
pub const widget_pin_complex: u8 = 0x04;

pub const widget_cap_stereo: u32 = 1 << 0;
pub const widget_cap_digital: u32 = 1 << 9;

/// One bounded codec graph.  Edges follow the HDA signal description from a
/// sink widget to the upstream source widgets in its expanded connection-list
/// order.  Keeping the expanded order is important because SET_CONNECT_SEL
/// addresses this order, including entries generated by range encoding.
pub const Graph = struct {
    present: [max_nodes]bool = .{false} ** max_nodes,
    afg: [max_nodes]u8 = .{0} ** max_nodes,
    kind: [max_nodes]u8 = .{0xff} ** max_nodes,
    caps: [max_nodes]u32 = .{0} ** max_nodes,
    connections_loaded: [max_nodes]bool = .{false} ** max_nodes,
    edge_start: [max_nodes]u16 = .{0} ** max_nodes,
    edge_count: [max_nodes]u16 = .{0} ** max_nodes,
    edges: [max_edges]u8 = .{0} ** max_edges,
    edge_len: u16 = 0,

    pub fn setNode(self: *Graph, node: u8, afg: u8, kind: u8, caps: u32) bool {
        if (node == 0 or afg == 0 or self.present[node]) return false;
        self.present[node] = true;
        self.afg[node] = afg;
        self.kind[node] = kind;
        self.caps[node] = caps;
        return true;
    }

    /// Expand one short- or long-form connection list.  Range entries include
    /// every NID after the preceding entry up to and including the range end.
    /// Malformed lists are rejected atomically.
    pub fn addEncodedConnectionList(self: *Graph, node: u8, long_form: bool, encoded: []const u16) bool {
        if (node == 0 or !self.present[node] or self.connections_loaded[node]) return false;
        if (encoded.len > 127) return false;

        const saved_len = self.edge_len;
        const start = self.edge_len;
        var previous: ?u16 = null;
        var previous_was_range = false;
        for (encoded) |raw| {
            const range_mask: u16 = if (long_form) 0x8000 else 0x0080;
            const node_mask: u16 = if (long_form) 0x7fff else 0x007f;
            if ((!long_form and (raw & 0xff00) != 0)) {
                self.edge_len = saved_len;
                return false;
            }
            const target = raw & node_mask;
            const is_range = (raw & range_mask) != 0;
            if (target == 0 or target >= max_nodes) {
                self.edge_len = saved_len;
                return false;
            }
            if (is_range) {
                const first = previous orelse {
                    self.edge_len = saved_len;
                    return false;
                };
                if (previous_was_range or target <= first) {
                    self.edge_len = saved_len;
                    return false;
                }
                var expanded = first + 1;
                while (expanded <= target) : (expanded += 1) {
                    if (!self.appendEdge(@intCast(expanded), start)) {
                        self.edge_len = saved_len;
                        return false;
                    }
                }
            } else if (!self.appendEdge(@intCast(target), start)) {
                self.edge_len = saved_len;
                return false;
            }
            previous = target;
            previous_was_range = is_range;
        }

        self.connections_loaded[node] = true;
        self.edge_start[node] = start;
        self.edge_count[node] = self.edge_len - start;
        return true;
    }

    fn appendEdge(self: *Graph, target: u8, start: u16) bool {
        if (@as(usize, self.edge_len) >= self.edges.len) return false;
        // A connection selector index is eight bits.  A legal HDA list can
        // contain at most 255 expanded entries.
        if (self.edge_len - start >= 255) return false;
        self.edges[self.edge_len] = target;
        self.edge_len += 1;
        return true;
    }

    pub fn connectionSlice(self: *const Graph, node: u8) []const u8 {
        if (!self.connections_loaded[node]) return &.{};
        const start: usize = self.edge_start[node];
        const count: usize = self.edge_count[node];
        return self.edges[start .. start + count];
    }

    /// Find the shortest deterministic analog route from a pin to an output
    /// converter.  Only mixers and selectors may be intermediate nodes.  Bad
    /// NIDs, cross-AFG edges, cycles and incomplete paths therefore fail
    /// closed without exhausting the bounded search.
    pub fn findAnalogOutputRoute(self: *const Graph, pin: u8) ?Route {
        var allowed = [_]bool{false} ** max_nodes;
        var node: usize = 0;
        while (node < max_nodes) : (node += 1) {
            allowed[node] = self.present[node] and
                self.kind[node] == widget_audio_output and
                (self.caps[node] & widget_cap_stereo) != 0 and
                (self.caps[node] & widget_cap_digital) == 0;
        }
        return self.findAnalogOutputRouteWithConverters(pin, &allowed);
    }

    pub fn findAnalogOutputRouteWithConverters(self: *const Graph, pin: u8, allowed_converters: *const [max_nodes]bool) ?Route {
        if (pin == 0 or !self.present[pin] or self.kind[pin] != widget_pin_complex) return null;
        const route_afg = self.afg[pin];
        var visited = [_]bool{false} ** max_nodes;
        var parent = [_]u8{0} ** max_nodes;
        var parent_connection = [_]u8{0} ** max_nodes;
        var queue = [_]u8{0} ** max_nodes;
        var read_index: usize = 0;
        var write_index: usize = 1;
        queue[0] = pin;
        visited[pin] = true;

        var converter: ?u8 = null;
        while (read_index < write_index) : (read_index += 1) {
            const sink = queue[read_index];
            const sources = self.connectionSlice(sink);
            for (sources, 0..) |source, connection_index| {
                if (source == 0 or !self.present[source] or self.afg[source] != route_afg) continue;
                if (visited[source]) continue;
                const source_kind = self.kind[source];
                const is_converter = source_kind == widget_audio_output and
                    (self.caps[source] & widget_cap_stereo) != 0 and
                    (self.caps[source] & widget_cap_digital) == 0 and
                    allowed_converters[source];
                const is_intermediate = (source_kind == widget_audio_mixer or source_kind == widget_audio_selector) and
                    (self.caps[source] & widget_cap_stereo) != 0;
                if (!is_converter and !is_intermediate) continue;

                visited[source] = true;
                parent[source] = sink;
                parent_connection[source] = @intCast(connection_index);
                if (is_converter) {
                    converter = source;
                    break;
                }
                if (write_index >= queue.len) return null;
                queue[write_index] = source;
                write_index += 1;
            }
            if (converter != null) break;
        }

        const found = converter orelse return null;
        var reverse = [_]u8{0} ** max_route_nodes;
        var count: usize = 0;
        var current = found;
        while (true) {
            if (count >= reverse.len) return null;
            reverse[count] = current;
            count += 1;
            if (current == pin) break;
            current = parent[current];
            if (current == 0) return null;
        }

        var route = Route{ .afg = route_afg, .count = @intCast(count) };
        var index: usize = 0;
        while (index < count) : (index += 1) {
            route.nodes[index] = reverse[count - 1 - index];
        }
        index = 0;
        while (index + 1 < count) : (index += 1) {
            route.connection_indices[index] = parent_connection[route.nodes[index + 1]];
        }
        return route;
    }
};

pub const Route = struct {
    afg: u8 = 0,
    count: u16 = 0,
    nodes: [max_route_nodes]u8 = .{0} ** max_route_nodes,
    connection_indices: [max_route_nodes - 1]u8 = .{0} ** (max_route_nodes - 1),

    pub fn pin(self: *const Route) u8 {
        return if (self.count == 0) 0 else self.nodes[0];
    }

    pub fn converter(self: *const Route) u8 {
        return if (self.count == 0) 0 else self.nodes[self.count - 1];
    }
};

fn testNode(graph: *Graph, node: u8, kind: u8) !void {
    const caps: u32 = if (kind == widget_audio_output or kind == widget_audio_mixer or
        kind == widget_audio_selector or kind == widget_pin_complex) widget_cap_stereo else 0;
    try std.testing.expect(graph.setNode(node, 1, kind, caps));
}

test "direct QEMU route keeps the exact connection index" {
    var graph = Graph{};
    try testNode(&graph, 2, widget_audio_output);
    try testNode(&graph, 3, widget_pin_complex);
    try std.testing.expect(graph.addEncodedConnectionList(3, false, &.{2}));
    const route = graph.findAnalogOutputRoute(3).?;
    try std.testing.expectEqual(@as(u16, 2), route.count);
    try std.testing.expectEqualSlices(u8, &.{ 3, 2 }, route.nodes[0..route.count]);
    try std.testing.expectEqual(@as(u8, 0), route.connection_indices[0]);
}

test "multistage mixer and selector route records every selection" {
    var graph = Graph{};
    try testNode(&graph, 2, widget_audio_output);
    try testNode(&graph, 7, widget_audio_mixer);
    try testNode(&graph, 8, widget_audio_selector);
    try testNode(&graph, 10, widget_pin_complex);
    try testNode(&graph, 20, 0x01);
    try std.testing.expect(graph.addEncodedConnectionList(10, false, &.{ 20, 8 }));
    try std.testing.expect(graph.addEncodedConnectionList(8, false, &.{ 7, 20 }));
    try std.testing.expect(graph.addEncodedConnectionList(7, false, &.{ 20, 2 }));
    const route = graph.findAnalogOutputRoute(10).?;
    try std.testing.expectEqualSlices(u8, &.{ 10, 8, 7, 2 }, route.nodes[0..route.count]);
    try std.testing.expectEqualSlices(u8, &.{ 1, 0, 1 }, route.connection_indices[0 .. route.count - 1]);
}

test "short and long range entries expand into selector order" {
    var short = Graph{};
    try testNode(&short, 2, widget_audio_output);
    try testNode(&short, 3, widget_audio_output);
    try testNode(&short, 4, widget_audio_output);
    try testNode(&short, 9, widget_pin_complex);
    try std.testing.expect(short.addEncodedConnectionList(9, false, &.{ 2, 0x84 }));
    try std.testing.expectEqualSlices(u8, &.{ 2, 3, 4 }, short.connectionSlice(9));

    var long = Graph{};
    try testNode(&long, 2, widget_audio_output);
    try testNode(&long, 3, widget_audio_output);
    try testNode(&long, 4, widget_audio_output);
    try testNode(&long, 9, widget_pin_complex);
    try std.testing.expect(long.addEncodedConnectionList(9, true, &.{ 2, 0x8004 }));
    try std.testing.expectEqualSlices(u8, &.{ 2, 3, 4 }, long.connectionSlice(9));
}

test "cycles and incomplete or invalid graphs fail closed" {
    var graph = Graph{};
    try testNode(&graph, 5, widget_audio_mixer);
    try testNode(&graph, 6, widget_audio_selector);
    try testNode(&graph, 9, widget_pin_complex);
    try std.testing.expect(graph.addEncodedConnectionList(9, false, &.{5}));
    try std.testing.expect(graph.addEncodedConnectionList(5, false, &.{6}));
    try std.testing.expect(graph.addEncodedConnectionList(6, false, &.{5}));
    try std.testing.expectEqual(@as(?Route, null), graph.findAnalogOutputRoute(9));

    var invalid = Graph{};
    try testNode(&invalid, 9, widget_pin_complex);
    try std.testing.expect(!invalid.addEncodedConnectionList(9, false, &.{0x82}));
    try std.testing.expectEqual(@as(u16, 0), invalid.edge_len);
}

test "converter filter skips an unsupported direct converter" {
    var graph = Graph{};
    try testNode(&graph, 2, widget_audio_output);
    try testNode(&graph, 3, widget_audio_output);
    try testNode(&graph, 9, widget_pin_complex);
    try std.testing.expect(graph.addEncodedConnectionList(9, false, &.{ 2, 3 }));
    var allowed = [_]bool{false} ** max_nodes;
    allowed[3] = true;
    const route = graph.findAnalogOutputRouteWithConverters(9, &allowed).?;
    try std.testing.expectEqualSlices(u8, &.{ 9, 3 }, route.nodes[0..route.count]);
    try std.testing.expectEqual(@as(u8, 1), route.connection_indices[0]);
}
